version: '3'
services:
  db:
    image: postgres:11.8-alpine
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
      - node_modules:/myapp/node_modules
    ports:
      - "3000:3000"
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: db
    depends_on:
      - db

volumes:
  db_data:
  bundle:
  node_modules:
